"""add_book_extraction_hints

Revision ID: 5506a0c35379
Revises: 81026c1a93e3
Create Date: 2026-05-10 06:41:18.074438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5506a0c35379'
down_revision: Union[str, None] = '81026c1a93e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
