"""add_book_conditions

Revision ID: 81026c1a93e3
Revises: 
Create Date: 2026-05-10 05:48:19.538256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '81026c1a93e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
